import './globals.css';
import '@repo/ui/src/styles.css';
import type { Metadata } from 'next';
import { Kulim_Park } from 'next/font/google';

const kulim = Kulim_Park({
  weight: ['200', '300', '400', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={kulim.className}>{children}</body>
    </html>
  );
}
